<?php
/*+***********************************************************************************
 * Demo4 — Custom module generated by FcvModuleBuilder
 ************************************************************************************/
class Demo4 extends CRMEntity {

    /** Required by vtlib — marks this as a user-created module */
    var $IsCustomModule = true;

    /** Used by CRMEntity::saveentity() and list/query methods */
    var $db;
    var $log;

    var $table_name  = 'vtiger_demo4';
    var $table_index = 'demo4id';

    var $tab_name = [
        'vtiger_crmentity',
        'vtiger_demo4',
        'vtiger_demo4cf',
    ];

    var $tab_name_index = [
        'vtiger_crmentity'   => 'crmid',
        'vtiger_demo4'   => 'demo4id',
        'vtiger_demo4cf' => 'demo4id',
    ];

    var $entity_table = 'vtiger_crmentity';

    /** Required for custom fields support */
    var $customFieldTable = ['vtiger_demo4cf', 'demo4id'];

    var $column_fields = [];

    var $additional_column_fields = ['smcreatorid', 'smownerid', 'crmid'];

    var $mandatory_fields = ['assigned_user_id', 'demo4name', 'createdtime', 'modifiedtime'];

    var $sortby_fields = [];

    var $list_fields = [
        'Name'        => ['demo4' => 'demo4name'],
        'Assigned To' => ['crmentity' => 'smownerid'],
    ];

    var $list_fields_name = [
        'Name'        => 'demo4name',
        'Assigned To' => 'assigned_user_id',
    ];

    var $list_link_field = 'demo4name';

    var $search_fields = [
        'Name'        => ['demo4' => 'demo4name'],
        'Assigned To' => ['crmentity' => 'smownerid'],
    ];

    var $search_fields_name = [
        'Name'        => 'demo4name',
        'Assigned To' => 'smownerid',
    ];

    var $def_basicsearch_col = 'demo4name';

    var $default_order_by   = 'demo4name';
    var $default_sort_order = 'ASC';

    var $module_name = 'Demo4';

    /**
     * Constructor — must initialise $this->db and $this->log so that
     * CRMEntity::saveentity() ($this->db->startTransaction()) does not
     * throw a fatal error (blank page on record save).
     */
    function __construct() {
        global $log;
        $this->column_fields = getColumnFields(get_class($this));
        $this->db  = PearDatabase::getInstance();
        $this->log = $log;
    }

    /** Required by CRMEntity — module-specific post-save hook */
    function save_module($module) {}
}