<?php
/*+***********************************************************************************
 * Demo5 — English language file (auto-generated by FcvModuleBuilder)
 ************************************************************************************/
$languageStrings = [
    'Demo5'          => 'Demo5',
    'SINGLE_Demo5'   => 'Demo5',
    'LBL_ADD_RECORD'         => 'Add Demo5',
    'LBL_RECORDS_LIST'       => 'Demo5 List',

    // Blocks
    'LBL_DEMO5_INFORMATION'            => 'Demo5 Information',
    'LBL_OTHER_INFORMATION'  => 'Other Information',

    // Field labels
    'Demo5 No'       => 'Demo5 No',
    'Name'                   => 'Name',
    'Assigned To'            => 'Assigned To',
    'Description'            => 'Description',
    'Created Time'           => 'Created Time',
    'Modified Time'          => 'Modified Time',
    'Last Modified By'       => 'Last Modified By',
    'Starred'                => 'Starred',
    'Tags'                   => 'Tags',
];

$jsLanguageStrings = [];