<?php
/*+***********************************************************************************
 * Demo4 — English language file (auto-generated by FcvModuleBuilder)
 ************************************************************************************/
$languageStrings = [
    'Demo4'          => 'Demo4',
    'SINGLE_Demo4'   => 'Demo4',
    'LBL_ADD_RECORD'         => 'Add Demo4',
    'LBL_RECORDS_LIST'       => 'Demo4 List',

    // Blocks
    'LBL_DEMO4_INFORMATION'            => 'Demo4 Information',
    'LBL_OTHER_INFORMATION'  => 'Other Information',

    // Field labels
    'Demo4 No'       => 'Demo4 No',
    'Name'                   => 'Name',
    'Assigned To'            => 'Assigned To',
    'Description'            => 'Description',
    'Created Time'           => 'Created Time',
    'Modified Time'          => 'Modified Time',
    'Last Modified By'       => 'Last Modified By',
    'Starred'                => 'Starred',
    'Tags'                   => 'Tags',
];

$jsLanguageStrings = [];